#! /bin/bash

# vdr recording rename from subtitle in info

#set -x

f=$1
f0=$(dirname $f)
cd $f0

if [ -e "$f/.timer" ]
then
    exit 8
fi

info=$f/info
if [ ! -e $info ]
then
    exit 8
fi

s=$(grep ^S $info)

#del="."
#if [[ "$t" == *\|* ]]
#then
#    del="|"
#fi
#del="|"
#exit

#s=$(echo $t | cut -d "$del" -f 1)
s=${s:2}
s=$(echo "$s"|tr ' ' '_')
s=$(echo "$s"|tr '/' '~')
if [ "$s" == "" ]
then
    s="_"
fi

echo $s

#exit

newdir=$f0/$s
#exit

echo $f "->" $newdir

t=$(find $f -type l)
if [ "$t" != "" ]
then
    echo "links inside"
    exit
fi
#exit
mkdir -p $newdir

mv $f $newdir
